// Build the annotate-mode client into a string module the content worker serves (the worker
// has no static-asset pipeline). Bundles client.ts → IIFE, reads client.css verbatim, and
// stamps a content version for cache-busting. Output: src/annotate/bundle.ts (committed).
//
// Run from packages/api:  bun run build:annotate
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = import.meta.dir
const srcDir = join(here, '..', 'src', 'annotate')

const built = await Bun.build({
  entrypoints: [join(srcDir, 'client.ts')],
  minify: true,
  format: 'iife',
  target: 'browser',
})
if (!built.success) {
  for (const log of built.logs) console.error(log)
  throw new Error('annotate client build failed')
}

const js = await built.outputs[0].text()
const css = readFileSync(join(srcDir, 'client.css'), 'utf8')
const version = new Bun.CryptoHasher('sha256').update(js + css).digest('hex').slice(0, 8)

const out = `// GENERATED by scripts/build-annotate.ts — do not edit by hand.
// Run \`bun run build:annotate\` after changing client.ts / client.css.
export const ANNOTATE_JS = ${JSON.stringify(js)}
export const ANNOTATE_CSS = ${JSON.stringify(css)}
export const ANNOTATE_VERSION = ${JSON.stringify(version)}
`
writeFileSync(join(srcDir, 'bundle.ts'), out)
console.log(`annotate bundle: ${js.length}B js + ${css.length}B css → v${version}`)
